language: python
jobs:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
      dist: xenial
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: xenial
    - python: 3.5
      dist: xenial
# command to run tests
script: python setup.py test
